import Head from "next/head";
import { NextPage } from "next";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to <a href="https://nextjs.org">Next.js!</a></h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Excepturi veniam repudiandae odit, similique nostrum rerum, necessitatibus, neque porro eius natus delectus deserunt consequuntur eaque perferendis. Impedit voluptatibus error nesciunt eum.</p>
      </main>
    </>
  );
}
